version: '3.8'
services:
  database:
    container_name: "${NEAR_ENV:-testnet}_database"
    image: auroraisnear/relayer-database
    restart: unless-stopped
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
  endpoint:
    container_name: "${NEAR_ENV:-testnet}_endpoint"
    image: auroraisnear/relayer-endpoint
    restart: unless-stopped
    init: true
    depends_on:
      - database
    environment:
      - WAIT_HOSTS=database:5432
      - WAIT_BEFORE=1
      - NEAR_ENV=${NEAR_ENV:-testnet}
      - NODE_ENV=${NEAR_ENV:-testnet}
    ports:
      - '127.0.0.1:8545:8545'
    volumes:
      - ./config:/srv/aurora/relayer/config
    entrypoint: ["node", "lib/index.js"]
volumes:
  database:
